# Generated by Django 4.1.13 on 2023-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("mainCategory", models.CharField(max_length=255)),
                ("subCategory", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("index", models.TextField()),
                ("s3Url", models.TextField()),
                ("createdAt", models.DateTimeField()),
                ("_class", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "cad",
            },
        ),
    ]
