# Generated by Django 4.1.13 on 2023-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cad",
            name="tfidf",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
