# Generated by Django 4.1.13 on 2023-11-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cad", "0002_alter_cad_tfidf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cad",
            old_name="classification",
            new_name="CadLabel",
        ),
        migrations.AlterField(
            model_name="cad",
            name="tfidf",
            field=models.TextField(default=""),
        ),
    ]
