# Generated by Django 4.2.7 on 2023-11-13 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cad", "0004_alter_cad__id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cad",
            old_name="CadLabel",
            new_name="cadLabel",
        ),
    ]
